### ISSUE TITLE
suggestion for TODO | having kube-ps1 display other things

### ISSUE THREAD

**Issue by georgettica** [mmazur/ccmux#1]
https://github.com/mmazur/ccmux/blob/a42b7621e12e65167a550fd8201df0bd812b8d1f/ccmux#L100

see
https://github.com/openshift/ocm-container/blob/master/utils/bashrc.d/06-sre-utils.bashrc
and
https://github.com/openshift/ocm-container/blob/master/utils/bashrc.d/04-kube-ps1.bashrc

on how to configure kube-ps1.sh to be custom

**Comment by mmazur** [comment]
Since there's a chance a version of this approach is going to be merged into osdctl with https://github.com/openshift/osdctl/pull/169 I'll likely switch my focus to making osdctl as close to what ccmux does now as possible.
